package gui;

import java.sql.*;
import conexionBD.Conexion;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anthony
 */
public class ActualizarPaciente extends javax.swing.JFrame {

    Conexion conexionBD = new Conexion();
    int cedula, telefono;
    String nombre, direccion, consulta, cedulaBD, nombreBD, direccionBD, telefonoBD, consultaBD;
    /**
     * Creates new form ActualizarPaciente
     */
    public ActualizarPaciente() {
        initComponents();
        textoCedula.setEditable(false);
        textNombre.setEditable(false);
        textDireccion.setEditable(false);
        textTelefono.setEditable(false);
        textConsulta.setEditable(false);
    }
    
    public JPanel getfondo(){
        return fondo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        textConsulta = new javax.swing.JTextField();
        textoCedula = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Actualizar Paciente");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 75, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Cédula del paciente:");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        textCedula.setBackground(new java.awt.Color(255, 255, 255));
        textCedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textCedula.setForeground(new java.awt.Color(0, 0, 0));
        textCedula.setBorder(null);
        fondo.add(textCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 220, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 230, 10));

        jButton1.setBackground(new java.awt.Color(166, 216, 189));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Cédula:");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Nombre:");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Dirección:");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Teléfono:");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Tipo de consulta:");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, -1, -1));

        jButton2.setBackground(new java.awt.Color(166, 216, 189));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Actualizar Paciente");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        fondo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, -1, 40));
        fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 200, 10));
        fondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 200, 10));
        fondo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 200, 10));
        fondo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 200, 10));
        fondo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 200, 10));

        textConsulta.setBackground(new java.awt.Color(255, 255, 255));
        textConsulta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textConsulta.setForeground(new java.awt.Color(0, 0, 0));
        textConsulta.setBorder(null);
        fondo.add(textConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 220, 30));

        textoCedula.setEditable(false);
        textoCedula.setBackground(new java.awt.Color(255, 255, 255));
        textoCedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textoCedula.setForeground(new java.awt.Color(0, 0, 0));
        textoCedula.setBorder(null);
        fondo.add(textoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 220, 30));

        textNombre.setBackground(new java.awt.Color(255, 255, 255));
        textNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textNombre.setForeground(new java.awt.Color(0, 0, 0));
        textNombre.setBorder(null);
        fondo.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 220, 30));

        textDireccion.setBackground(new java.awt.Color(255, 255, 255));
        textDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textDireccion.setForeground(new java.awt.Color(0, 0, 0));
        textDireccion.setBorder(null);
        fondo.add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 220, 30));

        textTelefono.setBackground(new java.awt.Color(255, 255, 255));
        textTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textTelefono.setForeground(new java.awt.Color(0, 0, 0));
        textTelefono.setBorder(null);
        fondo.add(textTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        boolean encontrado = false;
        
        //Validaciones del espacio de buscar cédula.
        if(textCedula.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar el campo.");
        }else if(!textCedula.getText().trim().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "El campo sólo puede contener números.");
        }else{
            
            //Instrucciones de la base de datos MySQL.
            cedula = Integer.parseInt(textCedula.getText());
            String checkCedula="select * from pacientes where cedula='"+cedula+"'";
            try{
                conexionBD.conectar();
                Statement st = conexionBD.cn.createStatement();
                ResultSet rs = st.executeQuery(checkCedula);

                while(rs.next()){
                    
                    textNombre.setEditable(true);
                    textDireccion.setEditable(true);
                    textTelefono.setEditable(true);
                    textConsulta.setEditable(true);
                    
                    cedulaBD = rs.getString("cedula");
                    nombreBD = rs.getString("nombre");
                    direccionBD = rs.getString("direccion");
                    telefonoBD = rs.getString("telefono");
                    consultaBD = rs.getString("tipo_consulta");

                    textoCedula.setText(cedulaBD);
                    textNombre.setText(nombreBD);
                    textDireccion.setText(direccionBD);
                    textTelefono.setText(telefonoBD);
                    textConsulta.setText(consultaBD);
                    encontrado = true;
                }
                if(encontrado == false){
                    JOptionPane.showMessageDialog(null, "No existe este número de cédula registrado en el sistema.");
                    textoCedula.setText("");
                    textNombre.setText("");
                    textDireccion.setText("");
                    textTelefono.setText("");
                    textConsulta.setText("");
                }
                conexionBD.desconectar();
            }catch(SQLException ex){
                System.out.println(ex.toString());
            }
            textCedula.setText("");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        //Validaciones de los espacios.
        if(textNombre.getText().trim().isEmpty() || textDireccion.getText().trim().isEmpty() || textTelefono.getText().trim().isEmpty() || textConsulta.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos.");
        }else if(!textTelefono.getText().trim().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "El campo de teléono sólo puede contener números.");
        }else{
            nombre = textNombre.getText();
            direccion = textDireccion.getText();
            telefono = Integer.parseInt(textTelefono.getText());
            consulta = textConsulta.getText();
            
            //Instrucciones de la base de datos MySQL.
            String query = "update pacientes set nombre='"+nombre+"',direccion='"+direccion+"',telefono='"+telefono+"',tipo_consulta='"+consulta+"' where cedula='"+cedulaBD+"'";

            try{
                conexionBD.conectar();
                Statement st = conexionBD.cn.createStatement();
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Información de paciente Actualizada.");
            }catch(SQLException ex){
                System.out.println(ex.toString());
            }

            textNombre.setText("");
            textDireccion.setText("");
            textTelefono.setText("");
            textConsulta.setText("");
            textNombre.setEditable(false);
            textDireccion.setEditable(false);
            textTelefono.setEditable(false);
            textConsulta.setEditable(false);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textConsulta;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JTextField textoCedula;
    // End of variables declaration//GEN-END:variables
}
