package gui;

import java.sql.*;
import conexionBD.Conexion;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anthony
 */
public class EliminarPaciente extends javax.swing.JFrame {

    Conexion conexionBD = new Conexion();
    int cedula= 0;
    /**
     * Creates new form EliminarPaciente
     */
    public EliminarPaciente() {
        initComponents();
    }
    
    public JPanel getfondo(){
        return fondo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Eliminar Paciente");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 75, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Cédula del paciente:");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        textCedula.setBackground(new java.awt.Color(255, 255, 255));
        textCedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textCedula.setBorder(null);
        fondo.add(textCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 220, 30));
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 230, 10));

        jButton1.setBackground(new java.awt.Color(166, 216, 189));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        //Validaciones de los espacios.
        if(textCedula.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar el campo.");
        }else if(!textCedula.getText().trim().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "El campo sólo puede contener números.");
        }else{
            cedula = Integer.parseInt(textCedula.getText());
            
            //Instrucciones de la base de datos MySQL.
            String checkCedula="select * from pacientes where cedula='"+cedula+"'";
            String eliminaPaciente="delete from pacientes where cedula='"+cedula+"'";

            try {
                conexionBD.conectar();
                Statement st = conexionBD.cn.createStatement();
                ResultSet rs = st.executeQuery(checkCedula);

                if(rs.next()){
                    st.executeUpdate(eliminaPaciente);
                    JOptionPane.showMessageDialog(null, "Paciente con cédula "+cedula+" eliminado del sistema.");
                }else{
                    JOptionPane.showMessageDialog(null, "No existe este número de cédula registrado en el sistema.");
                }
                conexionBD.desconectar();
            }catch(SQLException ex){
                     System.out.println(ex.toString());   
            }
            textCedula.setText("");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textCedula;
    // End of variables declaration//GEN-END:variables
}
