package gui;

import java.sql.*;
import conexionBD.Conexion;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anthony
 */
public class IngresarPaciente extends javax.swing.JFrame {

    int cedula=0;
    String nombre="";
    String direccion="";
    int telefono=0;
    String consulta="";
    
    Conexion conexionBD = new Conexion();
    
    public IngresarPaciente() {
        initComponents();
    }
    
    public JPanel getfondo(){
        return fondo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textConsulta = new javax.swing.JTextField();
        textCedula = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Ingresar Paciente");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 75, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de consulta:");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Nombre completo: ");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Cédula:");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Dirección:");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Número de teléfono:");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        textConsulta.setBackground(new java.awt.Color(255, 255, 255));
        textConsulta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textConsulta.setForeground(new java.awt.Color(0, 0, 0));
        textConsulta.setBorder(null);
        fondo.add(textConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 270, 30));

        textCedula.setBackground(new java.awt.Color(255, 255, 255));
        textCedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textCedula.setForeground(new java.awt.Color(0, 0, 0));
        textCedula.setToolTipText("");
        textCedula.setBorder(null);
        fondo.add(textCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, 30));

        textNombre.setBackground(new java.awt.Color(255, 255, 255));
        textNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textNombre.setForeground(new java.awt.Color(0, 0, 0));
        textNombre.setBorder(null);
        fondo.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 270, 30));

        textDireccion.setBackground(new java.awt.Color(255, 255, 255));
        textDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textDireccion.setForeground(new java.awt.Color(0, 0, 0));
        textDireccion.setBorder(null);
        fondo.add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 270, 30));

        textTelefono.setBackground(new java.awt.Color(255, 255, 255));
        textTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textTelefono.setForeground(new java.awt.Color(0, 0, 0));
        textTelefono.setBorder(null);
        fondo.add(textTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 270, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 310, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        fondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 310, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        fondo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 310, 40));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        fondo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 310, 40));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        fondo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 310, 40));

        jButton1.setBackground(new java.awt.Color(166, 216, 189));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        //Se valida que no hayan espacios en blanco ni letras en espacios donde sólo van números.
        if(textCedula.getText().trim().isEmpty() || textNombre.getText().trim().isEmpty() ||textDireccion.getText().trim().isEmpty() ||textTelefono.getText().trim().isEmpty() ||textConsulta.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
        }else if(!textCedula.getText().trim().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "El campo de cédula sólo puede contener números.");
        }else if(!textTelefono.getText().trim().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "El campo de Número de Teléfono sólo puede contener números.");
        }else{
            cedula = Integer.parseInt(textCedula.getText());
            nombre = textNombre.getText();
            direccion = textDireccion.getText();
            telefono = Integer.parseInt(textTelefono.getText());
            consulta = textConsulta.getText();

            //Instrucciones para la base de datos MySQL.
            String checkCedula = "select * from pacientes where cedula='"+cedula+"'";
            String query = "insert into pacientes (cedula,nombre,direccion,telefono,tipo_consulta) values ('"+cedula+"','"+nombre+"','"+direccion+"','"+telefono+"','"+consulta+"')";

            try{
                conexionBD.conectar();
                Statement st = conexionBD.cn.createStatement();
                ResultSet rs = st.executeQuery(checkCedula);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Este número de cédula ya se encuentra registrado en el sistema.");
                }else{
                    st.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Paciente ingresado al sistema.");
                }
                conexionBD.desconectar();
            }catch(SQLException ex){
                ex.printStackTrace();
            }
            
            textCedula.setText("");
            textNombre.setText("");
            textDireccion.setText("");
            textTelefono.setText("");
            textConsulta.setText("");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textConsulta;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
